### ISSUE TITLE
Building docker image stuck at step 8 / bower

### ISSUE THREAD

**Issue by adrianharabula** [adius/docker-ledger-web#2]
```
Step 8/11 : run bower --allow-root install
 ---> Running in 6270fdda1252
bower nvd3#*                not-cached git://github.com/novus/nvd3.git#*
bower nvd3#*                   resolve git://github.com/novus/nvd3.git#*
bower backbone.marionette#~1.4.1       not-cached https://github.com/marionettejs/backbone.marionette.git#~1.4.1
bower backbone.marionette#~1.4.1          resolve https://github.com/marionettejs/backbone.marionette.git#~1.4.1
bower react#~0.8.0                     not-cached https://github.com/facebook/react-bower.git#~0.8.0
bower react#~0.8.0                        resolve https://github.com/facebook/react-bower.git#~0.8.0
bower requirejs#~2.1.9                 not-cached https://github.com/jrburke/requirejs-bower.git#~2.1.9
bower requirejs#~2.1.9                    resolve https://github.com/jrburke/requirejs-bower.git#~2.1.9
bower handlebars#~1.2.1                not-cached https://github.com/components/handlebars.js.git#~1.2.1
bower handlebars#~1.2.1                   resolve https://github.com/components/handlebars.js.git#~1.2.1
bower requirejs-tpl#*                  not-cached https://github.com/ZeeAgency/requirejs-tpl.git#*
bower requirejs-tpl#*                     resolve https://github.com/ZeeAgency/requirejs-tpl.git#*
bower jquery#~2.0.3                    not-cached https://github.com/jquery/jquery-dist.git#~2.0.3
bower jquery#~2.0.3                       resolve https://github.com/jquery/jquery-dist.git#~2.0.3
bower bootstrap#~2.3.2                 not-cached https://github.com/twbs/bootstrap.git#~2.3.2
bower bootstrap#~2.3.2                    resolve https://github.com/twbs/bootstrap.git#~2.3.2
bower modernizr#~2.7.1                 not-cached https://github.com/Modernizr/Modernizr.git#~2.7.1
bower modernizr#~2.7.1                    resolve https://github.com/Modernizr/Modernizr.git#~2.7.1
bower nvd3#*                             download https://github.com/novus/nvd3/archive/v1.8.6.tar.gz
bower handlebars#~1.2.1                  download https://github.com/components/handlebars.js/archive/v1.2.1.tar.gz
bower react#~0.8.0                       download https://github.com/facebook/react-bower/archive/v0.8.0.tar.gz
bower requirejs#~2.1.9                   download https://github.com/jrburke/requirejs-bower/archive/2.1.22.tar.gz
bower backbone.marionette#~1.4.1         download https://github.com/marionettejs/backbone.marionette/archive/v1.4.1.tar.gz
bower requirejs-tpl#*                    download https://github.com/ZeeAgency/requirejs-tpl/archive/master.tar.gz
bower jquery#~2.0.3                      download https://github.com/jquery/jquery-dist/archive/2.0.3.tar.gz
bower modernizr#~2.7.1                   download https://github.com/Modernizr/Modernizr/archive/v2.7.2.tar.gz
bower handlebars#~1.2.1                   extract archive.tar.gz
bower requirejs#~2.1.9                    extract archive.tar.gz
bower nvd3#*                              extract archive.tar.gz
bower requirejs#~2.1.9                   resolved https://github.com/jrburke/requirejs-bower.git#2.1.22
bower handlebars#~1.2.1                  resolved https://github.com/components/handlebars.js.git#1.2.1
bower requirejs-tpl#*                     extract archive.tar.gz
bower requirejs-tpl#*                    resolved https://github.com/ZeeAgency/requirejs-tpl.git#7438735aa8
bower react#~0.8.0                        extract archive.tar.gz
bower react#~0.8.0                       resolved https://github.com/facebook/react-bower.git#0.8.0
bower jquery#~2.0.3                       extract archive.tar.gz
bower modernizr#~2.7.1                    extract archive.tar.gz
bower backbone.marionette#~1.4.1          extract archive.tar.gz
bower nvd3#*                             resolved git://github.com/novus/nvd3.git#1.8.6
bower d3#^3.4.4                        not-cached https://github.com/mbostock-bower/d3-bower.git#^3.4.4
bower d3#^3.4.4                           resolve https://github.com/mbostock-bower/d3-bower.git#^3.4.4
bower jquery#~2.0.3                      resolved https://github.com/jquery/jquery-dist.git#2.0.3
bower modernizr#~2.7.1                   resolved https://github.com/Modernizr/Modernizr.git#2.7.2
bower bootstrap#~2.3.2                   download https://github.com/twbs/bootstrap/archive/v2.3.2.tar.gz
bower d3#^3.4.4                          download https://github.com/mbostock-bower/d3-bower/archive/v3.5.17.tar.gz
bower backbone.marionette#~1.4.1         resolved https://github.com/marionettejs/backbone.marionette.git#1.4.1
bower backbone#~1.1.0                  not-cached https://github.com/jashkenas/backbone.git#~1.1.0
bower backbone#~1.1.0                     resolve https://github.com/jashkenas/backbone.git#~1.1.0
bower underscore#~1.5.1                not-cached https://github.com/jashkenas/underscore.git#~1.5.1
bower underscore#~1.5.1                   resolve https://github.com/jashkenas/underscore.git#~1.5.1
bower d3#^3.4.4                           extract archive.tar.gz
bower underscore#~1.5.1                  download https://github.com/jashkenas/underscore/archive/1.5.2.tar.gz
bower d3#^3.4.4                          resolved https://github.com/mbostock-bower/d3-bower.git#3.5.17
bower backbone#~1.1.0                    download https://github.com/jashkenas/backbone/archive/1.1.2.tar.gz
bower underscore#~1.5.1                   extract archive.tar.gz
bower underscore#~1.5.1                  resolved https://github.com/jashkenas/underscore.git#1.5.2
bower bootstrap#~2.3.2                    extract archive.tar.gz
bower bootstrap#~2.3.2                   resolved https://github.com/twbs/bootstrap.git#2.3.2
bower backbone#~1.1.0                     extract archive.tar.gz
bower backbone#~1.1.0                    resolved https://github.com/jashkenas/backbone.git#1.1.2
bower requirejs#~2.1.9                    install requirejs#2.1.22
bower handlebars#~1.2.1                   install handlebars#1.2.1
bower requirejs-tpl#*                     install requirejs-tpl#7438735aa8
bower react#~0.8.0                        install react#0.8.0
bower nvd3#*                              install nvd3#1.8.6
bower jquery#~2.0.3                       install jquery#2.0.3
bower modernizr#~2.7.1                    install modernizr#2.7.2
bower backbone.marionette#~1.4.1          install backbone.marionette#1.4.1
bower d3#^3.4.4                           install d3#3.5.17
bower underscore#~1.5.1                   install underscore#1.5.2
bower bootstrap#~2.3.2                    install bootstrap#2.3.2
bower backbone#~1.1.0                     install backbone#1.1.2

requirejs#2.1.22 bower_components/requirejs

handlebars#1.2.1 bower_components/handlebars

requirejs-tpl#7438735aa8 bower_components/requirejs-tpl

react#0.8.0 bower_components/react

nvd3#1.8.6 bower_components/nvd3
└── d3#3.5.17

jquery#2.0.3 bower_components/jquery

modernizr#2.7.2 bower_components/modernizr

backbone.marionette#1.4.1 bower_components/backbone.marionette
├── backbone#1.1.2
└── underscore#1.5.2

d3#3.5.17 bower_components/d3

underscore#1.5.2 bower_components/underscore

bootstrap#2.3.2 bower_components/bootstrap
└── jquery#2.0.3

backbone#1.1.2 bower_components/backbone
└── underscore#1.5.2
Removing intermediate container 6270fdda1252
 ---> 250fa76f4353
Step 9/11 : run grunt
 ---> Running in 244a30250c5b
Running "copy:vendor" (copy) task
Copied 11 files

Running "recess:dist" (recess) task
File "public/css/main.css" created.
Original: 148100 bytes.
Minified: 123142 bytes.

Running "requirejs:compile" (requirejs) task
{ Error: Error: Module loading did not complete for: main, income/module, income/controller, income/income-vs-expenditure-chart, charting/multi-bar-chart, nvd3, spending/module, spending/controller, spending/expenditure-chart, worth/module, worth/controller, worth/net-worth-chart, charting/line-plus-bar-chart, balance/module, balance/controller, balance/chart, charting/pie-chart
    at Function.build.checkForErrors (/node-ledger-web/node_modules/requirejs/bin/r.js:31556:19)

    at /node-ledger-web/node_modules/requirejs/bin/r.js:30099:19
    at /node-ledger-web/node_modules/requirejs/bin/r.js:3081:39
    at /node-ledger-web/node_modules/requirejs/bin/r.js:3021:25
    at Function.prim.nextTick (/node-ledger-web/node_modules/requirejs/bin/r.js:29929:9)
    at Object.errback (/node-ledger-web/node_modules/requirejs/bin/r.js:3020:26)
    at Object.callback (/node-ledger-web/node_modules/requirejs/bin/r.js:3006:23)
    at Object.then (/node-ledger-web/node_modules/requirejs/bin/r.js:3060:23)
    at build (/node-ledger-web/node_modules/requirejs/bin/r.js:30056:12)
    at runBuild (/node-ledger-web/node_modules/requirejs/bin/r.js:32006:17)
    at Object.execCb (/node-ledger-web/node_modules/requirejs/bin/r.js:1941:33)
  originalError: 
   Error: Module loading did not complete for: main, income/module, income/controller, income/income-vs-expenditure-chart, charting/multi-bar-chart, nvd3, spending/module, spending/controller, spending/expenditure-chart, worth/module, worth/controller, worth/net-worth-chart, charting/line-plus-bar-chart, balance/module, balance/controller, balance/chart, charting/pie-chart
       at Function.build.checkForErrors (/node-ledger-web/node_modules/requirejs/bin/r.js:31556:19)
       at Function.build.traceDependencies (/node-ledger-web/node_modules/requirejs/bin/r.js:31440:19)
       at /node-ledger-web/node_modules/requirejs/bin/r.js:30284:38
       at /node-ledger-web/node_modules/requirejs/bin/r.js:3114:24
       at /node-ledger-web/node_modules/requirejs/bin/r.js:3063:37
       at /node-ledger-web/node_modules/requirejs/bin/r.js:3011:25
       at Function.prim.nextTick (/node-ledger-web/node_modules/requirejs/bin/r.js:29929:9)
       at Object.callback (/node-ledger-web/node_modules/requirejs/bin/r.js:3010:26)
       at Object.then (/node-ledger-web/node_modules/requirejs/bin/r.js:3060:23)
       at /node-ledger-web/node_modules/requirejs/bin/r.js:3113:29 }
The command '/bin/sh -c grunt' returned a non-zero code: 1
```

**Comment by ad-si** [comment]
The upstream repository (https://github.com/slashdotdash/node-ledger-web) is unfortunately no longer maintained, so I'm closing this issue.
